### ISSUE TITLE
How to set kubectl for non-root user

### ISSUE THREAD

**Issue by sdanishgcp** [ghodss/kubernetes-macosx-development#16]
I am getting this error for non-root user on centos 7 .For root it is giving correct result. 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Error from server (Forbidden): <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fversion'/><script>window.location.replace('/login?from=%2Fversion');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:
  
Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>
```

**Comment by ghodss** [comment]
It seems as though Kubernetes is not running on the IP and port that you've pointed kubectl at, and you're hitting some other software instead. Did you run `export KUBERNETES_MASTER=10.1.2.3:8080` before using kubectl?

**Comment by sdanishgcp** [comment]
Hi,
Thanks for reply which was helpful. I have checked what you suggested. 

For root user the credentials was set by default and i was not setting credentials for the non root user before running the kubectl version . It is running now for non root user now.

**Comment by batreseau** [comment]
How did you resolve it ?

Can you explain me how did you grant access to kubectl (bash) for other user ?

I have a user "Control" who need to interact whith kubectl, but if i'm not Root, i can't start Kube CLI (kubectl).

**Comment by madhunarne** [comment]
The cluster might not be running when the command was issued but if you try after cluster is up, you should get the version without any issues ..

kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by praveenpetfect** [comment]
> I am getting this error for non-root user on centos 7 .For root it is giving correct result.
> 
> ```
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
> Error from server (Forbidden): <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fversion'/><script>window.location.replace('/login?from=%2Fversion');</script></head><body style='background-color:white; color:white;'>
> 
> 
> Authentication required
> 
> 
> </body></html>
> ```

how to resolve this?

**Comment by azagramac** [comment]
```
root@linux minikube# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Error from server (Forbidden): <html><head><meta http-equiv='refresh' content='1;url=/login?from=%2Fversion%3Ftimeout%3D32s'/><script>window.location.replace('/login?from=%2Fversion%3Ftimeout%3D32s');</script></head><body style='background-color:white; color:white;'>


Authentication required
<!--
You are authenticated as: anonymous
Groups that you are in:

Permission you need to have (but didn't): hudson.model.Hudson.Read
 ... which is implied by: hudson.security.Permission.GenericRead
 ... which is implied by: hudson.model.Hudson.Administer
-->

</body></html>
```
