### ISSUE TITLE
kubectl version giving "connection refused"

### ISSUE THREAD

**Issue by arun-gupta** [ghodss/kubernetes-macosx-development#8]
```
[vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh version
Running: ./cluster/../_output/local/bin/linux/amd64/kubectl version
Couldn't read version from server: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: connection refused
```

**Comment by arun-gupta** [comment]
Other commands are giving similar error too.

```
./cluster/kubectl.sh get pods
Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
F0113 20:12:27.586043    2638 get.go:75] Get http://localhost:8080/api/v1beta1/pods?namespace=default: dial tcp 127.0.0.1:8080: connection refused
```

**Comment by ghodss** [comment]
Thanks for the report - should be fixed in https://github.com/ghodss/kubernetes-macosx-development/commit/5b84ef7688c76a60167f7962296020aff8cc620a.

**Comment by arun-gupta** [comment]
Now getting

```
[vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh version
Running: ./cluster/../_output/local/bin/linux/amd64/kubectl version
Couldn't read version from server: Get http://10.245.1.2:8080/version: dial tcp 10.245.1.2:8080: connection refused
```

**Comment by mcelligott** [comment]
+1 same issue using the vagrant setup as well

**Comment by schugh-gopivotal** [comment]
+1 I'm seeing the same issue with vagrant setup. I downloaded Kubernetes setup today.

**Comment by amitkgupta** [comment]
Followed the main docs for getting started with vagrant today, also getting:

```
agupta$ ./cluster/kubectl.sh get nodes
error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused
```

**Comment by rastapopulous** [comment]
+!

**Comment by jiasir** [comment]
+1 same issue using the Azure setup as well.

**Comment by jiasir** [comment]
Setting `KUBERNETES_MASTER=[your master ip]` environment to  be resolved.

**Comment by kinghadi** [comment]
I'm using local cluster. I've set the KUBERNETES_MASTER to master ip (ifconfig find the docker0 ip segment) I still get this error?! Ubuntu14.04 on VM

**Comment by ccarrero** [comment]
I did setup a two node local cluster using RedHat and the instructions from this link:
http://kubernetes.io/v1.0/docs/getting-started-guides/docker-multinode/master.html

All worked well as you can see:
# kubectl get nodes
NAME           LABELS                                STATUS
10.182.99.70   kubernetes.io/hostname=10.182.99.70   Ready
127.0.0.1      kubernetes.io/hostname=127.0.0.1      Ready
 
After that, I had to reboot both nodes, and at the end I had to follow the same instructions again. But now I am having similar error as the one in the thread.

[root@pilotvm37-2 ~]# kubectl get pods
error: couldn't read version from server: Get http://127.0.0.1/api: dial tcp 127.0.0.1:80: connection refused

This i what I have running:
[root@pilotvm37-2 ~]# docker ps -a
CONTAINER ID        IMAGE                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
75855ebe3afc        gcr.io/google_containers/hyperkube:v0.21.2   "/hyperkube scheduler"   About an hour ago   Up About an hour                        k8s_scheduler.b725e775_k8s-master-127.0.0.1_default_06b6b39e77c0de608e62b61a71d18205_b2a0552d
9543b1bea6ba        gcr.io/google_containers/hyperkube:v0.21.2   "/hyperkube apiserver"   About an hour ago   Up About an hour                        k8s_apiserver.fe80218_k8s-master-127.0.0.1_default_06b6b39e77c0de608e62b61a71d18205_7a5eae58
4c512371d150        gcr.io/google_containers/hyperkube:v0.21.2   "/hyperkube controlle"   About an hour ago   Up About an hour                        k8s_controller-manager.aad1ee8f_k8s-master-127.0.0.1_default_06b6b39e77c0de608e62b61a71d18205_963f5ceb
c97fada2d67a        gcr.io/google_containers/hyperkube:v0.21.2   "/hyperkube proxy --m"   About an hour ago   Up About an hour                        adoring_mestorf
ca4fbc325d34        gcr.io/google_containers/pause:0.8.0         "/pause"                 About an hour ago   Up About an hour                        k8s_POD.e4cc795_k8s-master-127.0.0.1_default_06b6b39e77c0de608e62b61a71d18205_cab75650
7257936bb698        gcr.io/google_containers/hyperkube:v0.21.2   "/hyperkube kubelet -"   About an hour ago   Up About an hour                        hungry_euclid
[root@pilotvm37-2 ~]#
