### ISSUE TITLE
When "$ hack/local-up-cluster.sh" execute, I have a error message.

### ISSUE THREAD

**Issue by bwahn** [ghodss/kubernetes-macosx-development#9]
I got error message
 See the License for the specific language governing permissions and
etcd version 2.0.0 or greater required.

[vagrant@k8s-env kubernetes]$

**Comment by bwahn** [comment]
I modified "local-up-cluster.sh".
$vi hack/local-up-cluster.sh
...
...
echo "Starting etcd"
#kube::etcd::start
etcd start
...
...

**Comment by ghodss** [comment]
I believe hack/local-up-cluster.sh was momentarily broken on kube HEAD, but is now fixed. See https://github.com/GoogleCloudPlatform/kubernetes/commit/449f9d915eda51c2d60cc28e4f9bc9d61457a45b

**Comment by bwahn** [comment]
Great, I will leave message after testing.
